#!/usr/bin/env ruby

require "bundler/setup"
require_relative "lib/birthdaybot"

require "pry"

def list_birthdays(birthdays)
  text = ""
  if birthdays.length > 0
    birthdays.each do |employee|
      text << "#{employee.first_name} #{employee.last_name} (#{employee.birthday.strftime("%A %-d %B")})\n"
    end
  else
    text << "None"
  end

  text
end

employees = Employees.new(api_key: ENV.fetch("BREATHE_API_KEY")).all

excludes  = File.read(Pathname(__dir__) / "excludes").lines
birthdays = Birthdays.new(employees: employees, excludes: excludes)

slack = Slack.new(webhook_url: ENV.fetch("SLACK_WEBHOOK_URL"))

message = ""

message << "*Upcoming birthdays:*\n"
message << list_birthdays(birthdays.upcoming)
message << "\n\n"
if birthdays.today.length > 0
  message << "*Happy birthday for today to:*\n"
  birthdays.today.each do |employee|
    message << "#{employee.first_name} #{employee.last_name}\n"
  end
end

slack.send(message)
